Class2
EvelynJane/Repo_Selenium pull request #3
Opened 2021-12-22 18:34 UTC by EvelynJane

This was tricky.

2021-12-23 16:19 UTC, ahsansiddiki requested changes

2021-12-23 16:19 UTC, ahsansiddiki commented on src/test/java/Class2/Class2_Homework.java
> +        boolean messengerContinueButtonIsEnabled = messengerContinueButton.isEnabled();
You missing Assertion here too. Otherwise looks good.

2021-12-23 16:19 UTC, ahsansiddiki commented on src/test/java/Class2/Class2_Homework.java
> +        boolean messengerFindYourAccountLinkIsDisplayed = messengerFindYourAccountLink.isDisplayed();
You missing Assertion here.

2021-12-27 18:31 UTC, EvelynJane commented on src/test/java/Class2/Class2_Homework.java
> +        boolean messengerContinueButtonIsEnabled = messengerContinueButton.isEnabled();
Assert is on line 145

2021-12-27 22:43 UTC, ahsansiddiki approved these changes

2021-12-27 22:43 UTC, merged